[global]
current_project = 333
excel_sheet_mode = all
compass_sheet_mode = all

[Проект1]
output_folder = D:/Temp/111/pdf
merged_pdf_path = D:/Temp/111/pdf/Объединенный.pdf
add_page_numbers = yes
start_from_page3 = yes
source_folder = D:/Temp/111
source_files_1 = D:/Temp/111/Документ1.docx | all | enabled | merge
source_files_2 = D:/Temp/111/Таблица1.xlsx | all | enabled | merge
source_files_3 = D:/Temp/111/Чертеж1.cdw | all | enabled | merge

