[template]
input_folder = D:/PSB/Project
source_folder = _input_folder_
output_folder = _input_folder_/TEMPLATE/pdf
merged_pdf_path = _input_folder_/TEMPLATE/pdf/TEMPLATE.pdf
# source_files_1 = _input_folder_/Документ1.docx | all | enabled | merge

############################

# source_folder - папка с исходными файлами;
# путь к этой папке является путем, по которому первоначально открываются диалоги.
# input_folder - путь к папке, прописанный в template.ini, который служит для создания
# предварительных дефолтных начальных путей в setup.ini при создании нового проекта.
# С помощью команд меню Файл эти пути при необходимости уточняются.
# TEMPLATE - имя проекта, введенное при его создании по команде Создать проект.